finalize final

diff --git a/.github/workflows/modularized_build_final.yml b/.github/workflows/modularized_build_final.yml
--- a/.github/workflows/modularized_build_final.yml
+++ b/.github/workflows/modularized_build_final.yml
@@ -56,45 +56,45 @@ jobs:
         with:
           name: failure_file
           path: FAILURE.TXT
-                 
+
       - name: Build with Gradle
         run: ./gradlew assembleAndroidTest -x lint
-      
+
       - name: upload sample app artifact
         uses: actions/upload-artifact@v2
         with:
-            name: sample
-            path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk
+          name: sample
+          path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: core
-            path: core/build/outputs/apk/androidTest/debug/core-debug-androidTest.apk
+          name: core
+          path: core/build/outputs/apk/androidTest/debug/core-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: mobile-engage
-            path: mobile-engage/build/outputs/apk/androidTest/debug/mobile-engage-debug-androidTest.apk
+          name: mobile-engage
+          path: mobile-engage/build/outputs/apk/androidTest/debug/mobile-engage-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: predict
-            path: predict/build/outputs/apk/androidTest/debug/predict-debug-androidTest.apk
+          name: predict
+          path: predict/build/outputs/apk/androidTest/debug/predict-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: emarsys
-            path: emarsys/build/outputs/apk/androidTest/debug/emarsys-debug-androidTest.apk
+          name: emarsys
+          path: emarsys/build/outputs/apk/androidTest/debug/emarsys-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: emarsys-sdk
-            path: emarsys-sdk/build/outputs/apk/androidTest/debug/emarsys-sdk-debug-androidTest.apk
+          name: emarsys-sdk
+          path: emarsys-sdk/build/outputs/apk/androidTest/debug/emarsys-sdk-debug-androidTest.apk
 
       - name: create testlab services json
         uses: jsdaniell/create-json@1.1.2
@@ -149,8 +149,8 @@ jobs:
           name: failure_file
           path: FAILURE.TXT
 
-  CreateReleaseApk:
-    name: Create release apk
+  CreateReleaseBundle:
+    name: Create release bundle
     needs: Build
     runs-on: ubuntu-latest
     steps:
@@ -175,14 +175,14 @@ jobs:
           echo "${{ secrets.ANDROID_KEYSTORE }}" > mobile-team-android.jks.asc
                     gpg -d --passphrase "${{ secrets.ANDROID_GPG_PASSWORD }}" --batch mobile-team-android.jks.asc > sample/mobile-team-android.jks
 
-      - name: Release sample app with Gradle
-        run: ./gradlew assembleRelease
+      - name: Create release sample app with Gradle
+        run: ./gradlew :sample:bundleRelease
 
-      - name: Upload APK
+      - name: Upload bundle
         uses: actions/upload-artifact@v2
         with:
-           name: mobile-sdk-sample
-           path: sample/build/outputs/apk/release/sample-release.apk
+          name: mobile-sdk-sample
+          path: sample/build/outputs/bundle/release/sample-release.aab
 
       - name: Create file 'FAILURE.TXT' and write 'true' into it
         if: ${{ failure() }}
@@ -219,7 +219,7 @@ jobs:
       - name: Run tests
         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
         with:
-          arg-spec: 'testWithAllDevices.yml:core'
+          arg-spec: 'testWithSomeVirtualDevices.yml:core'
         env:
           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
 
@@ -258,7 +258,7 @@ jobs:
       - name: Run tests
         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
         with:
-          arg-spec: 'testWithAllDevices.yml:mobile-engage'
+          arg-spec: 'testWithSomeVirtualDevices.yml:mobile-engage'
         env:
           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
 
@@ -297,7 +297,7 @@ jobs:
       - name: Run tests
         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
         with:
-          arg-spec: 'testWithAllDevices.yml:predict'
+          arg-spec: 'testWithSomeVirtualDevices.yml:predict'
         env:
           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
 
@@ -339,7 +339,7 @@ jobs:
       - name: Run tests
         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
         with:
-          arg-spec: 'testWithAllDevices.yml:emarsys-sdk'
+          arg-spec: 'testWithSomeVirtualDevices.yml:emarsys-sdk'
         env:
           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
 
@@ -355,76 +355,90 @@ jobs:
           path: FAILURE.TXT
 
   TestEmarsys:
-      name: Run emarsys tests on Firebase
-      needs: Build
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v2.3.1
-          with:
-            submodules: true
-            fetch-depth: 0 # 0 indicates all history
-        - run: git fetch --all || echo "==> Accept any result"
+    name: Run emarsys tests on Firebase
+    needs: Build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2.3.1
+        with:
+          submodules: true
+          fetch-depth: 0 # 0 indicates all history
+      - run: git fetch --all || echo "==> Accept any result"
 
-        - name: Download sample app
-          uses: actions/download-artifact@v2
-          with:
-            name: sample
+      - name: Download sample app
+        uses: actions/download-artifact@v2
+        with:
+          name: sample
 
-        - name: Download core tests
-          uses: actions/download-artifact@v2
-          with:
-            name: emarsys
+      - name: Download core tests
+        uses: actions/download-artifact@v2
+        with:
+          name: emarsys
 
-        - name: Run tests
-          uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-          with:
-            arg-spec: 'testWithAllDevices.yml:emarsys'
-          env:
-            SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
+      - name: Run tests
+        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
+        with:
+          arg-spec: 'testWithSomeVirtualDevices.yml:emarsys'
+        env:
+          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
 
-        - name: Create file 'FAILURE.TXT' and write 'true' into it
-          if: ${{ failure() }}
-          run: echo 'true' > FAILURE.TXT
+      - name: Create file 'FAILURE.TXT' and write 'true' into it
+        if: ${{ failure() }}
+        run: echo 'true' > FAILURE.TXT
 
-        - name: Upload file 'FAILURE.TXT' as an artifact
-          if: ${{ failure() }}
-          uses: actions/upload-artifact@v1
-          with:
-            name: failure_file
-            path: FAILURE.TXT
+      - name: Upload file 'FAILURE.TXT' as an artifact
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v1
+        with:
+          name: failure_file
+          path: FAILURE.TXT
 
   ReleaseSample:
-      name: Release sample app
-      runs-on: ubuntu-latest
-      needs: [Build, TestCore, TestMobileEngage, TestPredict, TestEmarsysSDK, TestEmarsys, CreateReleaseApk, GradleLint]
-      steps:
-         - uses: actions/checkout@v2.3.1
-           with:
-              submodules: true
-              fetch-depth: 0 # 0 indicates all history
-         - run: git fetch --all || echo "==> Accept any result"
+    name: Release sample app
+    runs-on: ubuntu-latest
+    needs: [Build, TestCore, TestMobileEngage, TestPredict, TestEmarsysSDK, TestEmarsys, CreateReleaseBundle, GradleLint]
+    steps:
+      - uses: actions/checkout@v2.3.1
+        with:
+          submodules: true
+          fetch-depth: 0 # 0 indicates all history
+      - run: git fetch --all || echo "==> Accept any result"
 
-         - name: Download sample app
-           uses: actions/download-artifact@v2
-           with:
-             name: mobile-sdk-sample
-             path: tmpdir
+      - name: Download sample app
+        uses: actions/download-artifact@v2
+        with:
+          name: mobile-sdk-sample
+          path: tmpdir
+      #TODO delete this step
+      - name: upload to s3
+        uses: jakejarvis/s3-sync-action@master
+        with:
+          args: --acl public-read --follow-symlinks
 
-         - name: upload to s3
-           uses: jakejarvis/s3-sync-action@master
-           with:
-            args: --acl public-read --follow-symlinks
+      - name: create-google services json
+        uses: jsdaniell/create-json@1.1.2
+        with:
+          name: google-play-services.json
+          json: ${{ secrets.GOOGLE_PLAY_STORE_SEVICE_ACCOUNT_JSON }}
 
-         - name: Create file 'FAILURE.TXT' and write 'true' into it
-           if: ${{ failure() }}
-           run: echo 'true' > FAILURE.TXT
+      - name: Playstore upload
+        uses: r0adkll/upload-google-play@v1
+        with:
+          serviceAccountJson: google-play-services.json
+          packageName: com.emarsys.sample
+          releaseFile: tmpdir/sample-release.aab
+          track: alpha
 
-         - name: Upload file 'FAILURE.TXT' as an artifact
-           if: ${{ failure() }}
-           uses: actions/upload-artifact@v1
-           with:
-             name: failure_file
-             path: FAILURE.TXT
+      - name: Create file 'FAILURE.TXT' and write 'true' into it
+        if: ${{ failure() }}
+        run: echo 'true' > FAILURE.TXT
+
+      - name: Upload file 'FAILURE.TXT' as an artifact
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v1
+        with:
+          name: failure_file
+          path: FAILURE.TXT
 
   SlackNotification:
     name: Send slack notification
