release workflow start

diff --git a/.github/workflows/modularized_build.yml b/.github/workflows/modularized_build.yml
--- a/.github/workflows/modularized_build.yml
+++ b/.github/workflows/modularized_build.yml
@@ -41,11 +41,11 @@ jobs:
       - name: create-google services json
         uses: jsdaniell/create-json@1.1.2
         with:
-          # The name of the file to be written. | file.json 
+          # The name of the file to be written. | file.json
           name: google-services.json
-          # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}" 
+          # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}"
           json: ${{ secrets.GOOGLE_SERVICES_JSON }}
-          # Optional subfolder directory to save the json file. | src/ 
+          # Optional subfolder directory to save the json file. | src/
           dir: sample
 
       - name: Create file 'FAILURE.TXT' and write 'false' into it
@@ -56,105 +56,53 @@ jobs:
         with:
           name: failure_file
           path: FAILURE.TXT
-                 
+
       - name: Build with Gradle
         run: ./gradlew assembleAndroidTest -x lint
-      
+
       - name: upload sample app artifact
         uses: actions/upload-artifact@v2
         with:
-            name: sample
-            path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk
-
-#       - name: upload emarsys-sdk test apk artifact
-#         uses: actions/upload-artifact@v2
-#         with:
-#             name: core-api
-#             path: core-api/build/outputs/apk/androidTest/debug/core-api-debug-androidTest.apk
+          name: sample
+          path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: core
-            path: core/build/outputs/apk/androidTest/debug/core-debug-androidTest.apk
-
-#       - name: upload emarsys-sdk test apk artifact
-#         uses: actions/upload-artifact@v2
-#         with:
-#             name: mobile-engage-api
-#             path: mobile-engage-api/build/outputs/apk/androidTest/debug/mobile-engage-api-debug-androidTest.apk
+          name: core
+          path: core/build/outputs/apk/androidTest/debug/core-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: mobile-engage
-            path: mobile-engage/build/outputs/apk/androidTest/debug/mobile-engage-debug-androidTest.apk
-
-#       - name: upload emarsys-sdk test apk artifact
-#         uses: actions/upload-artifact@v2
-#         with:
-#             name: predict-api
-#             path: predict-api/build/outputs/apk/androidTest/debug/predict-api-debug-androidTest.apk
+          name: mobile-engage
+          path: mobile-engage/build/outputs/apk/androidTest/debug/mobile-engage-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: predict
-            path: predict/build/outputs/apk/androidTest/debug/predict-debug-androidTest.apk
+          name: predict
+          path: predict/build/outputs/apk/androidTest/debug/predict-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: emarsys
-            path: emarsys/build/outputs/apk/androidTest/debug/emarsys-debug-androidTest.apk
+          name: emarsys
+          path: emarsys/build/outputs/apk/androidTest/debug/emarsys-debug-androidTest.apk
 
       - name: upload emarsys-sdk test apk artifact
         uses: actions/upload-artifact@v2
         with:
-            name: emarsys-sdk
-            path: emarsys-sdk/build/outputs/apk/androidTest/debug/emarsys-sdk-debug-androidTest.apk
+          name: emarsys-sdk
+          path: emarsys-sdk/build/outputs/apk/androidTest/debug/emarsys-sdk-debug-androidTest.apk
 
       - name: create testlab services json
         uses: jsdaniell/create-json@1.1.2
         with:
-          # The name of the file to be written. | file.json 
-          name: sacc_key.json
-          # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}" 
-          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-      - name: Create file 'FAILURE.TXT' and write 'true' into it
-        if: ${{ failure() }}
-        run: echo 'true' > FAILURE.TXT
-
-      - name: Upload file 'FAILURE.TXT' as an artifact
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@v1
-        with:
-          name: failure_file
-          path: FAILURE.TXT
-
-  GradleLint:
-    name: Run lint on project
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2.3.1
-        with:
-          submodules: true
-          fetch-depth: 0 # 0 indicates all history
-      - run: git fetch --all || echo "==> Accept any result"
-
-      - name: create-google services json
-        uses: jsdaniell/create-json@1.1.2
-        with:
           # The name of the file to be written. | file.json
-          name: google-services.json
+          name: sacc_key.json
           # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}"
-          json: ${{ secrets.GOOGLE_SERVICES_JSON }}
-          # Optional subfolder directory to save the json file. | src/
-          dir: sample
-
-      - name: Lint project with Gradle
-        run: ./gradlew lint
+          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
 
       - name: Create file 'FAILURE.TXT' and write 'true' into it
         if: ${{ failure() }}
@@ -199,8 +147,8 @@ jobs:
       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
-           name: mobile-sdk-sample
-           path: sample/build/outputs/apk/release/sample-release.apk
+          name: mobile-sdk-sample
+          path: sample/build/outputs/apk/release/sample-release.apk
 
       - name: Create file 'FAILURE.TXT' and write 'true' into it
         if: ${{ failure() }}
@@ -212,338 +160,39 @@ jobs:
         with:
           name: failure_file
           path: FAILURE.TXT
-
-#   TestCoreApi:
-#     name: Run core-api tests on Firebase
-#     needs: Build
-#     runs-on: ubuntu-latest
-#     steps:
-#       - uses: actions/checkout@v2.3.1
-#         with:
-#           submodules: true
-#           fetch-depth: 0 # 0 indicates all history
-#       - run: git fetch --all || echo "==> Accept any result"
-#
-#       - name: Download sample app
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: sample
-#
-#       - name: Download core-api tests
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: core-api
-#
-#       - name: Run tests
-#         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-#         with:
-#           arg-spec: 'testWithAllDevices.yml:core-api'
-#         env:
-#           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-#
-#       - name: Create file 'FAILURE.TXT' and write 'true' into it
-#         if: ${{ failure() }}
-#         run: echo 'true' > FAILURE.TXT
-#
-#       - name: Upload file 'FAILURE.TXT' as an artifact
-#         if: ${{ failure() }}
-#         uses: actions/upload-artifact@v1
-#         with:
-#           name: failure_file
-#           path: FAILURE.TXT
-
-  TestCore:
-    name: Run core tests on Firebase
-    needs: Build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2.3.1
-        with:
-          submodules: true
-          fetch-depth: 0 # 0 indicates all history
-      - run: git fetch --all || echo "==> Accept any result"
-
-      - name: Download sample app
-        uses: actions/download-artifact@v2
-        with:
-          name: sample
-
-      - name: Download core tests
-        uses: actions/download-artifact@v2
-        with:
-          name: core
-
-      - name: Run tests
-        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-        with:
-          arg-spec: 'testWithAllDevices.yml:core'
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-      - name: Create file 'FAILURE.TXT' and write 'true' into it
-        if: ${{ failure() }}
-        run: echo 'true' > FAILURE.TXT
-
-      - name: Upload file 'FAILURE.TXT' as an artifact
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@v1
-        with:
-          name: failure_file
-          path: FAILURE.TXT
-
-#   TestMobileEngageApi:
-#     name: Run mobile-engage-api tests on Firebase
-#     needs: Build
-#     runs-on: ubuntu-latest
-#     steps:
-#       - uses: actions/checkout@v2.3.1
-#         with:
-#           submodules: true
-#           fetch-depth: 0 # 0 indicates all history
-#       - run: git fetch --all || echo "==> Accept any result"
-
-#       - name: Download sample app
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: sample
-
-#       - name: Download core tests
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: mobile-engage-api
-
-#       - name: Run tests
-#         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-#         with:
-#           arg-spec: 'testWithAllDevices.yml:mobile-engage-api'
-#         env:
-#           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-  TestMobileEngage:
-    name: Run mobile-engage tests on Firebase
-    needs: Build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2.3.1
-        with:
-          submodules: true
-          fetch-depth: 0 # 0 indicates all history
-      - run: git fetch --all || echo "==> Accept any result"
-
-      - name: Download sample app
-        uses: actions/download-artifact@v2
-        with:
-          name: sample
-
-      - name: Download core tests
-        uses: actions/download-artifact@v2
-        with:
-          name: mobile-engage
-
-      - name: Run tests
-        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-        with:
-          arg-spec: 'testWithAllDevices.yml:mobile-engage'
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-      - name: Create file 'FAILURE.TXT' and write 'true' into it
-        if: ${{ failure() }}
-        run: echo 'true' > FAILURE.TXT
-
-      - name: Upload file 'FAILURE.TXT' as an artifact
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@v1
-        with:
-          name: failure_file
-          path: FAILURE.TXT
-#
-#   TestPredictApi:
-#     name: Run predict-api tests on Firebase
-#     needs: Build
-#     runs-on: ubuntu-latest
-#     steps:
-#       - uses: actions/checkout@v2.3.1
-#         with:
-#           submodules: true
-#           fetch-depth: 0 # 0 indicates all history
-#       - run: git fetch --all || echo "==> Accept any result"
-#
-#       - name: Download sample app
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: sample
-#
-#       - name: Download core tests
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: predict-api
-#
-#       - name: Run tests
-#         uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-#         with:
-#           arg-spec: 'testWithAllDevices.yml:predict-api'
-#         env:
-#           SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-  TestPredict:
-    name: Run predict tests on Firebase
-    needs: Build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2.3.1
-        with:
-          submodules: true
-          fetch-depth: 0 # 0 indicates all history
-      - run: git fetch --all || echo "==> Accept any result"
-
-      - name: Download sample app
-        uses: actions/download-artifact@v2
-        with:
-          name: sample
-
-      - name: Download core tests
-        uses: actions/download-artifact@v2
-        with:
-          name: predict
-
-      - name: Run tests
-        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-        with:
-          arg-spec: 'testWithAllDevices.yml:predict'
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-      - name: Create file 'FAILURE.TXT' and write 'true' into it
-        if: ${{ failure() }}
-        run: echo 'true' > FAILURE.TXT
-
-      - name: Upload file 'FAILURE.TXT' as an artifact
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@v1
-        with:
-          name: failure_file
-          path: FAILURE.TXT
-
-  TestEmarsysSDK:
-    name: Run emarsys-sdk tests on Firebase
-    needs: Build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2.3.1
-        with:
-          submodules: true
-          fetch-depth: 0 # 0 indicates all history
-      - run: git fetch --all || echo "==> Accept any result"
-
-      - name: Download sample app
-        uses: actions/download-artifact@v2
-        with:
-          name: sample
-
-      - name: Download emarsys-sdk tests
-        uses: actions/download-artifact@v2
-        with:
-          name: emarsys-sdk
-
-      - name: Display structure of downloaded files
-        run: ls -R
-
-      - name: Run tests
-        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-        with:
-          arg-spec: 'testWithAllDevices.yml:emarsys-sdk'
-        env:
-          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-      - name: Create file 'FAILURE.TXT' and write 'true' into it
-        if: ${{ failure() }}
-        run: echo 'true' > FAILURE.TXT
-
-      - name: Upload file 'FAILURE.TXT' as an artifact
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@v1
-        with:
-          name: failure_file
-          path: FAILURE.TXT
-
-  TestEmarsys:
-      name: Run emarsys tests on Firebase
-      needs: Build
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v2.3.1
-          with:
-            submodules: true
-            fetch-depth: 0 # 0 indicates all history
-        - run: git fetch --all || echo "==> Accept any result"
-
-        - name: Download sample app
-          uses: actions/download-artifact@v2
-          with:
-            name: sample
-
-        - name: Download core tests
-          uses: actions/download-artifact@v2
-          with:
-            name: emarsys
-
-        - name: Run tests
-          uses: asadmansr/Firebase-Test-Lab-Action@v1.0
-          with:
-            arg-spec: 'testWithAllDevices.yml:emarsys'
-          env:
-            SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
-
-        - name: Create file 'FAILURE.TXT' and write 'true' into it
-          if: ${{ failure() }}
-          run: echo 'true' > FAILURE.TXT
-
-        - name: Upload file 'FAILURE.TXT' as an artifact
-          if: ${{ failure() }}
-          uses: actions/upload-artifact@v1
-          with:
-            name: failure_file
-            path: FAILURE.TXT
 
   ReleaseSample:
-      name: Release sample app
-      runs-on: ubuntu-latest
-      needs: [Build, TestCore, TestMobileEngage, TestPredict, TestEmarsysSDK, TestEmarsys, CreateReleaseApk, GradleLint]
-      steps:
-         - uses: actions/checkout@v2.3.1
-           with:
-              submodules: true
-              fetch-depth: 0 # 0 indicates all history
-         - run: git fetch --all || echo "==> Accept any result"
+    name: Release sample app
+    runs-on: ubuntu-latest
+    needs: [Build, CreateReleaseApk]
+    steps:
+      - uses: actions/checkout@v2.3.1
+        with:
+          submodules: true
+          fetch-depth: 0 # 0 indicates all history
+      - run: git fetch --all || echo "==> Accept any result"
 
-         - name: Download sample app
-           uses: actions/download-artifact@v2
-           with:
-             name: mobile-sdk-sample
-             path: tmpdir
+      - name: Download sample app
+        uses: actions/download-artifact@v2
+        with:
+          name: mobile-sdk-sample
+          path: tmpdir
 
-#        - name: Move release apk to folder
-#          shell: bash
-#          run: |
-#            mkdir tmpdir
-#            mv mobile-sdk-sample tmpdir/sample-release.apk
+      - name: upload to s3
+        uses: jakejarvis/s3-sync-action@master
+        with:
+          args: --acl public-read --follow-symlinks
 
-         - name: upload to s3
-           uses: jakejarvis/s3-sync-action@master
-           with:
-            args: --acl public-read --follow-symlinks
+      - name: Create file 'FAILURE.TXT' and write 'true' into it
+        if: ${{ failure() }}
+        run: echo 'true' > FAILURE.TXT
 
-         - name: Create file 'FAILURE.TXT' and write 'true' into it
-           if: ${{ failure() }}
-           run: echo 'true' > FAILURE.TXT
-
-         - name: Upload file 'FAILURE.TXT' as an artifact
-           if: ${{ failure() }}
-           uses: actions/upload-artifact@v1
-           with:
-             name: failure_file
-             path: FAILURE.TXT
+      - name: Upload file 'FAILURE.TXT' as an artifact
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v1
+        with:
+          name: failure_file
+          path: FAILURE.TXT
 
   SlackNotification:
     name: Send slack notification
@@ -582,6 +231,8 @@ jobs:
         uses: rtCamp/action-slack-notify@master
         env:
           SLACK_COLOR: '#FF3C00'
-          SLACK_MESSAGE: 'Build failed! :man-gesturing-no:'
+          SLACK_MESSAGE:
+            'Build failed! :man-gesturing-no: \n https://console.firebase.google.com/u/0/project/ems-mobile-sdk/testlab/histories/'
+
 
 
