lint it1!!!

diff --git a/.github/workflows/modularized_build.yml b/.github/workflows/modularized_build.yml
--- a/.github/workflows/modularized_build.yml
+++ b/.github/workflows/modularized_build.yml
@@ -57,7 +57,7 @@ jobs:
           name: failure_file
           path: FAILURE.TXT
                  
-      - name: Build + Lint with Gradle
+      - name: Build with Gradle
         run: ./gradlew assembleAndroidTest -x lint
       
       - name: upload sample app artifact
@@ -121,6 +121,31 @@ jobs:
           name: sacc_key.json
           # The json string that can be a secret of the github repo or a string of a json. | "{"title": "my json"}" 
           json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
+
+      - name: Create file 'FAILURE.TXT' and write 'true' into it
+        if: ${{ failure() }}
+        run: echo 'true' > FAILURE.TXT
+
+      - name: Upload file 'FAILURE.TXT' as an artifact
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v1
+        with:
+          name: failure_file
+          path: FAILURE.TXT
+
+  GradleLint:
+    name: Run lint on project
+    needs: Build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2.3.1
+        with:
+          submodules: true
+          fetch-depth: 0 # 0 indicates all history
+      - run: git fetch --all || echo "==> Accept any result"
+
+      - name: Lint project with Gradle
+        run: ./gradlew lint
 
       - name: Create file 'FAILURE.TXT' and write 'true' into it
         if: ${{ failure() }}
@@ -475,7 +500,7 @@ jobs:
   ReleaseSample:
       name: Release sample app
       runs-on: ubuntu-latest
-      needs: [Build, TestCore, TestMobileEngage, TestPredict, TestEmarsysSDK, TestEmarsys, CreateReleaseApk]
+      needs: [Build, TestCore, TestMobileEngage, TestPredict, TestEmarsysSDK, TestEmarsys, CreateReleaseApk, GradleLint]
       steps:
          - uses: actions/checkout@v2.3.1
            with:
