unhappy path init

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,6 +22,16 @@ jobs:
         with:
           java-version: 1.8
 
+      - name: Create file 'SUCCESS.TXT' and write 'true' into it
+        run: echo 'true' > SUCCESS.TXT
+
+      - name: Upload file 'SUCCESS.TXT' as an artifact
+        uses: actions/upload-artifact@v1
+        with:
+          name: success_file
+          path: SUCCESS.TXT
+
+
       - name: echo
         shell: bash
         run: |
@@ -81,5 +91,37 @@ jobs:
         shell: bash
         run: |
           echo "Final job ran"
+
+  UnhappyFinal:
+    name: Final job
+    runs-on: ubuntu-latest
+    needs: [Build, One, Two]
+    if: always()
+    steps:
+      - uses: actions/checkout@v2.3.1
+        with:
+          submodules: true
+          fetch-depth: 0 # 0 indicates all history
+      - run: git fetch --all || echo "==> Accept any result"
+        -
+      - name: Download file 'SUCCESS.TXT' from artifact
+        uses: actions/download-artifact@v1
+        with:
+          name: success_file
+
+      - name: Read file 'SUCCESS.TXT' and set output parameter
+        id: set_output
+        run: echo "::set-output name=SUCCESS::$(<success_file/SUCCESS.TXT)"
+
+      - name: Run steps of Job Three
+        if: steps.set_output.outputs.SUCCESS == 'false'
+        run: echo "Some one of the test jobs failed!"
+
+
+
+      - name: echo
+        shell: bash
+        run: |
+          echo "Unhappy Final job ran"
 
 
