One job fail

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,7 +37,12 @@ jobs:
           submodules: true
           fetch-depth: 0 # 0 indicates all history
       - run: git fetch --all || echo "==> Accept any result"
-
+      - name: Try to fail
+          run: exit 1
+      - name: Echo if failed
+          if: ${{ failure() }}
+          run: |
+            echo "One job failed"
       - name: echo
         shell: bash
         run: |
